version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    ports: 
      - 25565:25565
    environment:
      MEMORY: "4G"
      TYPE: "VANILLA"
      MODE: "survival"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 25575
      OPS: "31607bed-732f-4fa8-be65-93b22e3d068e"
      MOTD: "Eli Sucks"
    restart: always
    volumes:
    - ${HOME}/minecraft_server/data:/data
